# Generated by Django 5.1.6 on 2025-04-22 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('DC', 'Dc'), ('Marvel', 'Marvel'), ('SHUEISHA', 'Shueisha')], max_length=20)),
                ('description', models.TextField()),
                ('original_price', models.IntegerField()),
                ('discounted_price', models.IntegerField()),
                ('rent_price', models.IntegerField(default=7)),
                ('comic_image', models.ImageField(upload_to='comic_images')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comic')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CT', 'Chhattisgarh'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OR', 'Odisha'), ('PB', 'Punjab'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TG', 'Telangana'), ('TR', 'Tripura'), ('UP', 'Uttar Pradesh'), ('UK', 'Uttarakhand'), ('WB', 'West Bengal'), ('AN', 'Andaman and Nicobar Islands'), ('CH', 'Chandigarh'), ('DN', 'Dadra and Nagar Haveli and Daman and Diu'), ('DL', 'Delhi'), ('JK', 'Jammu and Kashmir'), ('LA', 'Ladakh'), ('LD', 'Lakshadweep'), ('PY', 'Puducherry')], max_length=2)),
                ('pincode', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comic')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customerdetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comic_publisher', models.CharField(choices=[('DC', 'Dc'), ('MARVEL', 'Marvel'), ('SHUEISHA', 'Shueisha')], max_length=20)),
                ('published_at', models.DateField()),
                ('number_chapters', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('ONGOING', 'Ongoing')], default='ONGOING', max_length=20)),
                ('publisher_brand_logo', models.ImageField(upload_to='brand_images')),
                ('published_comic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.comic')),
            ],
        ),
        migrations.CreateModel(
            name='Rental_system',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_start_date', models.DateTimeField(auto_now_add=True)),
                ('rent_end_date', models.DateTimeField()),
                ('rental_status', models.CharField(choices=[('ACTIVE', 'active'), ('EXPIRED', 'expired'), ('NOT ISSUED', 'not issued')], default='NOT ISSUED', max_length=20)),
                ('rental_plan', models.CharField(choices=[('ONE_MONTH', 'one_month'), ('THREE_MONTH', 'three_month'), ('ONE_MINUTES', 'one minute'), ('30_SECONDS', '30_seconds')], max_length=20)),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_review', models.CharField(blank=True, max_length=200, null=True)),
                ('review_date', models.DateField(auto_now_add=True)),
                ('number_of_stars', models.PositiveIntegerField(default=0)),
                ('reviews_on_comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
